import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        This is the home page
        <ul>
          <li>
            <Link href="/portfolio">PortfolioPage</Link>
          </li>
          <li>
            <Link href="/clients">clientsPage</Link>
          </li>
        </ul>
      </main>
    </div>
  );
}

export default HomePage;
